parameters:
  - name: azureServiceConnection
    type: string

stages:
  - stage: Deploy
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    displayName: Deploy Api
    jobs:
      - job: Deploy
        displayName: Deploy Api
        pool:
          vmImage: $(vmImageName)
        condition: succeeded()
        steps:
          - task: AzureFunctionApp@1
            inputs:
              azureSubscription: ${{ parameters.azureServiceConnection }}
              appType: 'functionApp'
              appName: 'weather-data-api'
              package: '$(System.DefaultWorkingDirectory)/**/*.zip'
              deploymentMethod: 'auto'