pr: 
  - main
  
trigger:
  branches: 
    include: 
      - main
      - feat/deploy/azure

variables:
  vmImageName: 'ubuntu-latest'
  workingDirectory: '$(System.DefaultWorkingDirectory)/Backend/WeatherFunctionApp'

stages:
  - template: pipeline/stages/testAndBuild.yml
    parameters:
      azureServiceConnection: 'd37d7f8a-1de9-4233-8ca8-8fba70d644f4'

  - template: pipeline/stages/deployApi.yml
    parameters: 
      azureServiceConnection: 'd37d7f8a-1de9-4233-8ca8-8fba70d644f4'