pr: 
  - main
  
trigger:
  branches: 
    include: 
      - main
      - feat/deploy/azure

variables:
  vmImageName: 'ubuntu-latest'
  workingDirectory: '$(System.DefaultWorkingDirectory)/Backend/WeatherFunctionApp'

stages:
  - template: pipeline/stages/testAndBuild.yml
    parameters:
      azureServiceConnection: 'b057fd6f-72b4-4701-9330-32deb9830270'

  - template: pipeline/stages/deployApi.yml
    parameters: 
      azureServiceConnection: 'b057fd6f-72b4-4701-9330-32deb9830270'