pr: 
  - main
  
trigger:
  branches: 
    include: 
      - main
      - feat/deploy/azure

variables:
  vmImageName: 'ubuntu-latest'
  workingDirectory: '$(System.DefaultWorkingDirectory)/Backend/WeatherFunctionApp'

stages:
  - template: pipeline/stages/testAndBuild.yml
    parameters:
      azureServiceConnection: '9ab87f72-48d2-47f9-a7de-81aaf8416976'

  - template: pipeline/stages/deployApi.yml
    parameters: 
      azureServiceConnection: '9ab87f72-48d2-47f9-a7de-81aaf8416976'